version: '3'

services:
  database:
    image: postgres:10.5-alpine
    volumes:
      - ./server/db:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432

  server:
    build:
      context: ./server
    ports:
      - 5001:5001
    depends_on:
      - database
    entrypoint: dockerize -wait tcp://database:5432 -timeout 30s
    command: yarn start --web-socket=5001
    env_file:
      - .env
    volumes:
      - ./server/src:/srv/aql/src

  dashboard:
    build:
      context: ./dashboard
    ports:
      - 3000:3000
    depends_on:
      - server
    command: yarn start
    volumes:
      - ./dashboard/src:/srv/aql/src
